name: Build

on: [ push ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        working-directory: vertex-demo-app
        run: mvn --batch-mode --update-snapshots verify
